# Generated by Django 3.2.5 on 2021-07-14 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='computermodels',
            table='computers',
        ),
    ]
