# Generated by Django 3.2.5 on 2021-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_alter_computermodels_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('RAM', models.IntegerField()),
                ('CPU', models.FloatField()),
                ('display', models.IntegerField()),
            ],
            options={
                'verbose_name': 'computer',
                'db_table': 'computers',
            },
        ),
        migrations.DeleteModel(
            name='ComputerModels',
        ),
    ]
