# Generated by Django 3.2.5 on 2021-07-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carmodel_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'car'},
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
