# Generated by Django 3.2.5 on 2021-07-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
