# Generated by Django 3.2.5 on 2021-07-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0002_auto_20210719_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='computermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
