# Generated by Django 3.2.5 on 2021-07-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0003_auto_20210719_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComputerModel',
        ),
    ]
